### PR TITLE
Only specify Chdir command if it is needed

### LINKED ISSUE #72: Support `--recursive` flag
Hey, I have come across a problem when passing the `recursive` flag into the action. I get the following error

```
  Failed to find workspaces; cannot use --recursive and --chdir at the same time
```
which makes sense as [this](https://github.com/reviewdog/action-tflint/blob/master/script.sh#L101) line will always pass the `chdir` argument into the command. I am wondering if it is possible to add a flag to not send this if the user is specifying the `recursive` flag.  I am thinking of possibly not setting [tflint_target_dir](https://github.com/reviewdog/action-tflint/blob/master/action.yml#L48) to the default (as it shouldn't need to be passing in a `.` value anyway as it just indicates no changing of the directory) and only providing the command if there is a value provided.

I am happy to do the PR to get this change out, I am just seeking guidance on which way to approach this. 

A sample of how we run this command is 

```
      - name: Terraform Lint
        id: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          flags: "--enable-rule=terraform_unused_declarations --disable-rule=terraform_typed_variables --recursive"
          filter_mode: nofilter
          tflint_rulesets: "aws"
          level: "error
```

### PR DESCRIPTION
**Pull request by justmitch123**
Hey, this is a proposed PR to fix https://github.com/reviewdog/action-tflint/issues/72

I can update the documentation etc to match the change but just wanted to confirm that this is the best way to achieve this fix before writing the documentation etc for it

### CODE REVIEW

File: script.sh [hunk 1]
```diff
@@ -98,7 +98,17 @@ echo '::group:: Running tflint with reviewdog 🐶 ...'
   set +Eeuo pipefail
 
   # shellcheck disable=SC2086
-  TFLINT_PLUGIN_DIR=${TFLINT_PLUGIN_DIR} "${TFLINT_PATH}/tflint" -c "${INPUT_TFLINT_CONFIG}" --format=checkstyle ${INPUT_FLAGS} --chdir=${INPUT_TFLINT_TARGET_DIR} \
+
+  # We only want to specify the tflint target directory if it is not the default to avoid conflicts
+  export CHDIR_COMMAND=""
+  if [ "$INPUT_TFLINT_TARGET_DIR" == "." ]; then
+    echo "Using default wowrking directory. No need to specify chdir"
```
Comment (Sebelino) [inline script.sh]:
```suggestion
    echo "Using default working directory. No need to specify chdir."
```

File: script.sh [hunk 2]
```diff
@@ -98,7 +98,17 @@ echo '::group:: Running tflint with reviewdog 🐶 ...'
   set +Eeuo pipefail
 
   # shellcheck disable=SC2086
-  TFLINT_PLUGIN_DIR=${TFLINT_PLUGIN_DIR} "${TFLINT_PATH}/tflint" -c "${INPUT_TFLINT_CONFIG}" --format=checkstyle ${INPUT_FLAGS} --chdir=${INPUT_TFLINT_TARGET_DIR} \
+
+  # We only want to specify the tflint target directory if it is not the default to avoid conflicts
+  export CHDIR_COMMAND=""
```
Comment (Sebelino) [inline script.sh]:
```suggestion
  CHDIR_COMMAND=""
```
I believe `export` isn't needed here. This isn't an environment variable which you intend to make available to a child process of this script.

File: script.sh [hunk 3]
```diff
@@ -98,7 +98,17 @@ echo '::group:: Running tflint with reviewdog 🐶 ...'
...
+  if [ "$INPUT_TFLINT_TARGET_DIR" == "." ]; then
+    echo "Using default wowrking directory. No need to specify chdir"
+  else
+    echo "Custom target directory specified."
+  CHDIR_COMMAND="--chdir=${INPUT_TFLINT_TARGET_DIR}"
```
Comment (Sebelino) [inline script.sh]:
```suggestion
    CHDIR_COMMAND="--chdir=${INPUT_TFLINT_TARGET_DIR}"
```

File: script.sh [hunk 4]
```diff
@@ -98,7 +98,17 @@ echo '::group:: Running tflint with reviewdog 🐶 ...'
...
+  fi
+
+  TFLINT_PLUGIN_DIR=${TFLINT_PLUGIN_DIR} "${TFLINT_PATH}/tflint" -c "${INPUT_TFLINT_CONFIG}" --format=checkstyle ${INPUT_FLAGS} ${CHDIR_COMMAND} \
```
Comment (Sebelino) [inline script.sh:111]: **issue:** To suppress the shellcheck error, you need to move `# shellcheck disable=SC2086` on line 100 right above this line.

**Comment by justmitch123** [comment]
@Sebelino thankyou for your review. I have made the above changes

File: script.sh [hunk 5]
```diff
@@ -97,8 +97,18 @@ echo '::group:: Running tflint with reviewdog 🐶 ...'
...
+  if [ "$INPUT_TFLINT_TARGET_DIR" == "." ]; then
+    echo "Using default working directory. No need to specify chdir"
+  else
+    echo "Custom target directory specified."
+    CHDIR_COMMAND="--chdir=${INPUT_TFLINT_TARGET_DIR}"
+  fi
+
   # shellcheck disable=SC2086
-  TFLINT_PLUGIN_DIR=${TFLINT_PLUGIN_DIR} "${TFLINT_PATH}/tflint" -c "${INPUT_TFLINT_CONFIG}" --format=checkstyle ${INPUT_FLAGS} --chdir=${INPUT_TFLINT_TARGET_DIR} \
+  TFLINT_PLUGIN_DIR=${TFLINT_PLUGIN_DIR} "${TFLINT_PATH}/tflint" -c "${INPUT_TFLINT_CONFIG}" --format=checkstyle "${INPUT_FLAGS}" "${CHDIR_COMMAND}" \
```
Comment (Sebelino) [inline script.sh]: **issue:** We shouldn't surround `INPUT_FLAGS` and `CHDIR_COMMAND` with quotes in this particular case.

To show why, I can give an example. If `CHDIR_COMMAND` is set to an empty string (`""`), then the line
```bash
tflint ${CHDIR_COMMAND}
```
evaluates to:
```bash
tflint
```
which is a valid `tflint` command. OTOH, the line:
```bash
tflint "${CHDIR_COMMAND}"
```
would evaluate to
```bash
tflint ""
```
which would cause `tflint` to fail with the following error message:
```
Failed to parse CLI arguments; Failed to load ``: File not found
```
and a nonzero exit code.

ShellCheck normally complains if shellscripts contain variables that are not quoted, which is why we have added the `shellcheck disable=SC2086` line here.

Comment (justmitch123) [reply script.sh]: That makes sense - thanks

**Review by Sebelino — APPROVED** [review]
LGTM

**Comment by review-dog** [comment]
Hi, @mitchellharvey97! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!
